/**
 * Full category taxonomy for Pet Carrier: carriers, strollers and beds.
 * Every node here becomes a real page at /[path], generated by
 * app/[section]/[[...path]]/page.tsx. Content (intro, why-choose, sizing
 * guide, FAQ) is generated from the `animal` and `descriptor` fields by
 * lib/category-content.ts, so adding a node here is enough to publish a
 * fully SEO-ready page, no per-category prose required.
 */

export type Section = "carriers" | "strollers" | "beds";

export interface CategoryNode {
  path: string; // full URL path without leading slash, e.g. "carriers/dog-carriers/puppy-carriers"
  name: string; // display name / H1, e.g. "Puppy Carriers"
  section: Section;
  level: 1 | 2 | 3;
  parentPath: string | null;
  animal: string; // e.g. "dog", "cat", "rabbit", "multiple pets"
  descriptor: string; // who/what this category suits, used in generated copy
  kind: "hub" | "sub" | "collection";
}

function seg(parentPath: string, slug: string): string {
  return `${parentPath}/${slug}`;
}

function hub(
  section: Section,
  path: string,
  name: string,
  parentPath: string | null,
  level: 1 | 2 | 3,
  animal: string,
  descriptor: string
): CategoryNode {
  return { path, name, section, level, parentPath, animal, descriptor, kind: "hub" };
}

function sub(
  section: Section,
  parentPath: string,
  slug: string,
  name: string,
  level: 2 | 3,
  animal: string,
  descriptor: string
): CategoryNode {
  return {
    path: seg(parentPath, slug),
    name,
    section,
    level,
    parentPath,
    animal,
    descriptor,
    kind: "sub",
  };
}

function collection(
  section: Section,
  parentPath: string,
  slug: string,
  name: string,
  animal: string,
  descriptor: string
): CategoryNode {
  return {
    path: seg(parentPath, slug),
    name,
    section,
    level: 2,
    parentPath,
    animal,
    descriptor,
    kind: "collection",
  };
}

// ---------------------------------------------------------------------
// CARRIERS
// ---------------------------------------------------------------------

const carriersHub = hub(
  "carriers",
  "carriers",
  "Carriers",
  null,
  1,
  "multiple pets",
  "getting any pet from A to B safely and comfortably"
);

const dogCarriersHub = hub(
  "carriers",
  "carriers/dog-carriers",
  "Dog Carriers",
  "carriers",
  2,
  "dog",
  "dogs of every age and size, from puppies to larger breeds"
);
const dogCarrierSubs: CategoryNode[] = [
  sub("carriers", "carriers/dog-carriers", "puppy-carriers", "Puppy Carriers", 3, "dog", "young puppies who are still growing and getting used to the world"),
  sub("carriers", "carriers/dog-carriers", "puppy-slings", "Puppy Slings", 3, "dog", "very young puppies who need to be held close and reassured"),
  sub("carriers", "carriers/dog-carriers", "small-dog-carriers", "Small Dog Carriers", 3, "dog", "small dogs weighing up to around 10kg"),
  sub("carriers", "carriers/dog-carriers", "medium-dog-carriers", "Medium Dog Carriers", 3, "dog", "medium-sized dogs weighing roughly 10kg to 25kg"),
  sub("carriers", "carriers/dog-carriers", "large-dog-carriers", "Large Dog Carriers", 3, "dog", "larger dogs over around 25kg who need a sturdier, roomier carrier"),
  sub("carriers", "carriers/dog-carriers", "dog-slings", "Dog Slings", 3, "dog", "dogs who travel best held close against you in a sling"),
  sub("carriers", "carriers/dog-carriers", "dog-backpack-carriers", "Dog Backpack Carriers", 3, "dog", "hands-free days out with your dog carried on your back"),
  sub("carriers", "carriers/dog-carriers", "airline-approved-dog-carriers", "Airline Approved Dog Carriers", 3, "dog", "dogs flying in the cabin on UK and EU airlines"),
  sub("carriers", "carriers/dog-carriers", "dog-car-carriers", "Dog Car Carriers", 3, "dog", "safe, secure car journeys with your dog"),
  sub("carriers", "carriers/dog-carriers", "dog-bike-carriers", "Dog Bike Carriers", 3, "dog", "dogs who join you on bike rides"),
  sub("carriers", "carriers/dog-carriers", "hiking-dog-carriers", "Hiking Dog Carriers", 3, "dog", "dogs coming along on longer walks and hikes"),
  sub("carriers", "carriers/dog-carriers", "rolling-dog-carriers", "Rolling Dog Carriers", 3, "dog", "dogs who are more comfortable wheeled than carried"),
];

const catCarriersHub = hub(
  "carriers",
  "carriers/cat-carriers",
  "Cat Carriers",
  "carriers",
  2,
  "cat",
  "cats of every age, from nervous kittens to larger breeds"
);
const catCarrierSubs: CategoryNode[] = [
  sub("carriers", "carriers/cat-carriers", "kitten-carriers", "Kitten Carriers", 3, "cat", "young kittens who are still getting used to travel"),
  sub("carriers", "carriers/cat-carriers", "soft-sided-cat-carriers", "Soft-Sided Cat Carriers", 3, "cat", "cats who settle better in a softer, more flexible carrier"),
  sub("carriers", "carriers/cat-carriers", "hard-sided-cat-carriers", "Hard-Sided Cat Carriers", 3, "cat", "cats who need a little extra protection and structure"),
  sub("carriers", "carriers/cat-carriers", "cat-backpack-carriers", "Cat Backpack Carriers", 3, "cat", "hands-free travel with your cat carried on your back"),
  sub("carriers", "carriers/cat-carriers", "airline-approved-cat-carriers", "Airline Approved Cat Carriers", 3, "cat", "cats flying in the cabin on UK and EU airlines"),
  sub("carriers", "carriers/cat-carriers", "cat-slings", "Cat Slings", 3, "cat", "cats who feel safest held close against you"),
  sub("carriers", "carriers/cat-carriers", "large-cat-carriers", "Large Cat Carriers", 3, "cat", "larger cat breeds who need extra room to turn around"),
];

const smallAnimalCarriersHub = hub(
  "carriers",
  "carriers/small-animal-carriers",
  "Small Animal Carriers",
  "carriers",
  2,
  "small animal",
  "rabbits, guinea pigs, hamsters, ferrets and other small pets"
);
const smallAnimalCarrierSubs: CategoryNode[] = [
  sub("carriers", "carriers/small-animal-carriers", "rabbit-carriers", "Rabbit Carriers", 3, "rabbit", "rabbits, who need good ventilation and a solid base for hopping about"),
  sub("carriers", "carriers/small-animal-carriers", "guinea-pig-carriers", "Guinea Pig Carriers", 3, "guinea pig", "guinea pigs, who settle best with hay and familiar bedding close by"),
  sub("carriers", "carriers/small-animal-carriers", "hamster-carriers", "Hamster Carriers", 3, "hamster", "hamsters and other small rodents on short trips"),
  sub("carriers", "carriers/small-animal-carriers", "ferret-carriers", "Ferret Carriers", 3, "ferret", "ferrets, who are curious and need a secure, escape-proof carrier"),
  sub("carriers", "carriers/small-animal-carriers", "reptile-carriers", "Reptile Carriers", 3, "reptile", "reptiles, who need warmth and security while being transported"),
];

const birdCarriersHub = hub(
  "carriers",
  "carriers/bird-carriers",
  "Bird Carriers",
  "carriers",
  2,
  "bird",
  "budgies, parrots and other pet birds"
);
const birdCarrierSubs: CategoryNode[] = [
  sub("carriers", "carriers/bird-carriers", "budgie-travel-cages", "Budgie Travel Cages", 3, "budgie", "budgies and similarly sized small birds"),
  sub("carriers", "carriers/bird-carriers", "parrot-travel-cages", "Parrot Travel Cages", 3, "parrot", "parrots and larger birds who need more room to perch"),
  sub("carriers", "carriers/bird-carriers", "small-bird-carriers", "Small Bird Carriers", 3, "bird", "small pet birds on short, calm trips"),
];

const carrierCollections: CategoryNode[] = [
  collection("carriers", "carriers", "pet-airline-approved-carriers", "Airline Approved Pet Carriers", "multiple pets", "any pet flying in the cabin on UK and EU airlines"),
  collection("carriers", "carriers", "pet-backpack-carriers", "Pet Backpack Carriers", "multiple pets", "hands-free travel with your pet carried on your back"),
  collection("carriers", "carriers", "pet-rolling-carriers", "Pet Carriers with Wheels", "multiple pets", "pets who travel better wheeled than carried"),
  collection("carriers", "carriers", "pet-sling-carriers", "Pet Sling Carriers", "multiple pets", "pets who feel calmest held close in a sling"),
  collection("carriers", "carriers", "pet-hard-sided-carriers", "Hard-Sided Pet Carriers", "multiple pets", "pets who need a sturdier, more protective carrier"),
  collection("carriers", "carriers", "pet-soft-sided-carriers", "Soft-Sided Pet Carriers", "multiple pets", "pets who prefer a lighter, more flexible carrier"),
  collection("carriers", "carriers", "pet-carriers-for-vet-visits", "Pet Carriers for Vet Visits", "multiple pets", "short trips to the vet"),
  collection("carriers", "carriers", "pet-car-travel-carriers", "Pet Carriers for Car Travel", "multiple pets", "safe, secure car journeys"),
  collection("carriers", "carriers", "hiking-pet-carriers", "Hiking Pet Carriers", "multiple pets", "pets joining you on longer walks and hikes"),
  collection("carriers", "carriers", "everyday-pet-carriers", "Everyday Pet Carriers", "multiple pets", "everyday trips and errands with your pet"),
];

// ---------------------------------------------------------------------
// STROLLERS
// ---------------------------------------------------------------------

const strollersHub = hub(
  "strollers",
  "strollers",
  "Strollers",
  null,
  1,
  "multiple pets",
  "pets who enjoy fresh air on wheels, without the strain of a long walk"
);

const dogStrollersHub = hub(
  "strollers",
  "strollers/dog-strollers",
  "Dog Strollers",
  "strollers",
  2,
  "dog",
  "dogs who need a comfortable ride on wheels"
);
const dogStrollerSubs: CategoryNode[] = [
  sub("strollers", "strollers/dog-strollers", "small-dog-strollers", "Small Dog Strollers", 3, "dog", "small dogs and toy breeds"),
  sub("strollers", "strollers/dog-strollers", "large-dog-strollers", "Large Dog Strollers", 3, "dog", "larger dogs who need a sturdier stroller frame"),
  sub("strollers", "strollers/dog-strollers", "jogging-dog-strollers", "Jogging Dog Strollers", 3, "dog", "owners who want to bring their dog along on runs"),
  sub("strollers", "strollers/dog-strollers", "double-dog-strollers", "Double Dog Strollers", 3, "dog", "two dogs travelling together side by side"),
  sub("strollers", "strollers/dog-strollers", "puppy-strollers", "Puppy Strollers", 3, "dog", "young puppies not yet fully vaccinated or confidently mobile"),
];

const strollerStandalone: CategoryNode[] = [
  sub("strollers", "strollers", "cat-strollers", "Cat Strollers", 2, "cat", "cats who enjoy fresh air without the risks of walking outside"),
  sub("strollers", "strollers", "small-animal-strollers", "Small Animal Strollers", 2, "small animal", "small pets like rabbits and guinea pigs who enjoy the outdoors safely"),
  sub("strollers", "strollers", "multi-pet-strollers", "Multi-Pet Strollers", 2, "multiple pets", "households with more than one pet travelling together"),
];

// ---------------------------------------------------------------------
// BEDS
// ---------------------------------------------------------------------

const bedsHub = hub(
  "beds",
  "beds",
  "Beds",
  null,
  1,
  "multiple pets",
  "a comfortable, familiar place for your pet to rest"
);

const dogBedsHub = hub(
  "beds",
  "beds/dog-beds",
  "Dog Beds",
  "beds",
  2,
  "dog",
  "dogs who need a comfortable place to rest and recover"
);
const dogBedSubs: CategoryNode[] = [
  sub("beds", "beds/dog-beds", "puppy-beds", "Puppy Beds", 3, "dog", "growing puppies who need a soft, secure place to settle"),
  sub("beds", "beds/dog-beds", "small-dog-beds", "Small Dog Beds", 3, "dog", "small dog breeds"),
  sub("beds", "beds/dog-beds", "large-dog-beds", "Large Dog Beds", 3, "dog", "larger dog breeds who need more space to stretch out"),
  sub("beds", "beds/dog-beds", "orthopaedic-dog-beds", "Orthopaedic Dog Beds", 3, "dog", "older dogs or those with joint stiffness who need extra support"),
  sub("beds", "beds/dog-beds", "elevated-dog-beds", "Elevated Dog Beds", 3, "dog", "dogs who prefer to be raised off the floor, especially in warmer weather"),
  sub("beds", "beds/dog-beds", "travel-dog-beds", "Travel Dog Beds", 3, "dog", "dogs on the move who still need a familiar place to rest"),
];

const catBedsHub = hub(
  "beds",
  "beds/cat-beds",
  "Cat Beds",
  "beds",
  2,
  "cat",
  "cats who love to curl up somewhere cosy"
);
const catBedSubs: CategoryNode[] = [
  sub("beds", "beds/cat-beds", "kitten-beds", "Kitten Beds", 3, "cat", "young kittens who need a small, secure bed of their own"),
  sub("beds", "beds/cat-beds", "cat-cave-beds", "Cat Cave Beds", 3, "cat", "cats who love to hide away and feel enclosed"),
  sub("beds", "beds/cat-beds", "heated-cat-beds", "Heated Cat Beds", 3, "cat", "cats who feel the cold, especially older cats"),
  sub("beds", "beds/cat-beds", "window-cat-beds", "Window Cat Beds", 3, "cat", "cats who love to watch the world go by from a windowsill"),
];

const smallAnimalBedsHub = hub(
  "beds",
  "beds/small-animal-beds",
  "Small Animal Beds",
  "beds",
  2,
  "small animal",
  "small pets who need a cosy, familiar place to settle"
);
const smallAnimalBedSubs: CategoryNode[] = [
  sub("beds", "beds/small-animal-beds", "rabbit-beds", "Rabbit Beds", 3, "rabbit", "rabbits who need a soft, insulated place to rest"),
  sub("beds", "beds/small-animal-beds", "guinea-pig-beds", "Guinea Pig Beds", 3, "guinea pig", "guinea pigs who like to burrow somewhere warm"),
  sub("beds", "beds/small-animal-beds", "ferret-beds", "Ferret Beds", 3, "ferret", "ferrets, who often prefer to sleep tucked away and out of sight"),
];

const bedsStandalone: CategoryNode[] = [
  sub("beds", "beds", "travel-beds", "Travel Beds", 2, "multiple pets", "pets who need a familiar bed to bring along when travelling or staying away"),
];

export const CATEGORIES: CategoryNode[] = [
  carriersHub,
  dogCarriersHub,
  ...dogCarrierSubs,
  catCarriersHub,
  ...catCarrierSubs,
  smallAnimalCarriersHub,
  ...smallAnimalCarrierSubs,
  birdCarriersHub,
  ...birdCarrierSubs,
  ...carrierCollections,

  strollersHub,
  dogStrollersHub,
  ...dogStrollerSubs,
  ...strollerStandalone,

  bedsHub,
  dogBedsHub,
  ...dogBedSubs,
  catBedsHub,
  ...catBedSubs,
  smallAnimalBedsHub,
  ...smallAnimalBedSubs,
  ...bedsStandalone,
];

export const SECTIONS: { value: Section; name: string }[] = [
  { value: "carriers", name: "Carriers" },
  { value: "strollers", name: "Strollers" },
  { value: "beds", name: "Beds" },
];

export function getCategoryByPath(path: string): CategoryNode | undefined {
  return CATEGORIES.find((c) => c.path === path);
}

export function getChildren(path: string): CategoryNode[] {
  return CATEGORIES.filter((c) => c.parentPath === path);
}

export function getBreadcrumbTrail(path: string): CategoryNode[] {
  const trail: CategoryNode[] = [];
  let current = getCategoryByPath(path);
  while (current) {
    trail.unshift(current);
    current = current.parentPath ? getCategoryByPath(current.parentPath) : undefined;
  }
  return trail;
}

export function getRelatedCategories(path: string, limit = 4): CategoryNode[] {
  const node = getCategoryByPath(path);
  if (!node) return [];

  if (node.parentPath) {
    const siblings = CATEGORIES.filter((c) => c.parentPath === node.parentPath && c.path !== path);
    if (siblings.length >= limit) return siblings.slice(0, limit);
    const parent = getCategoryByPath(node.parentPath);
    return parent ? [parent, ...siblings].slice(0, limit) : siblings.slice(0, limit);
  }

  return getChildren(path).slice(0, limit);
}

export function getSectionHub(section: Section): CategoryNode {
  const found = CATEGORIES.find((c) => c.path === section);
  if (!found) throw new Error(`No hub category found for section ${section}`);
  return found;
}
